#ifndef CONFIG
#define CONFIG

#include "variables.h"

#define CONFIG_GPIO_BUTTON_PIN_1 2
#define CONFIG_GPIO_BUTTON_PIN_2 19
#define CONFIG_GPIO_LED_PIN 21

#define PIN_SDA 18
#define PIN_SCL 23

#define SHOW_SNIFFER_DEBUG 0
#define PRINT_BATTERY_STATUS 0
#define CONFIG_STATUS_LED 0
#define USE_OLED 1
#define FLIP_OLED 0
#define USE_BUTTONS 1

#define CONFIG_GPIO_LED_ON 0
#define CONFIG_GPIO_LED_OFF 1

#define SPAM_BUTTON_PERIOD 200
#define CONFIG_SHORT_OLED_PERIOD 10000
#define CONFIG_MEDIUM_OLED_PERIOD 30000
#define CONFIG_LONG_OLED_PERIOD 10000

#define OLED_POWER_PIN 27
#define BAT_POWER_PIN 4

#define CONFIG_WIFI_SSID "esp32wifi"
#define CONFIG_WIFI_PASSWORD "esp32test"

#define SERVER_WIFI_SSID "ESP32_Sniffer"
#define SERVER_WIFI_PASSWORD "12345678"

#define ESP_AP_IP "192.168.4.1"

#define CONFIG_SD_MOUNT_POINT "/sdcard"
#define CONFIG_SD_1_LINE true

#define CONFIG_PCAP_FILENAME_MASK "file_%06lu.pcap"
#define CONFIG_OUTPUT_FILE "REDUCED_DATA.csv"
#define CONFIG_BATTERY_FILE "BATTERY_DATA.csv"

#define CONFIG_SNIFFER_TASK_STACK_SIZE 4096
#define CONFIG_SNIFFER_TASK_PRIORITY 2
#define CONFIG_SNIFFER_WORK_QUEUE_LEN 128
#define CONFIG_SNIFFER_DEFAULT_CHANNEL 2

#define CONFIG_SNIFFER_USE_MAC_FILTER 0
#define CONFIG_SNIFFER_MAC_FILTER_B1 0x58
#define CONFIG_SNIFFER_MAC_FILTER_B2 0xBF
#define CONFIG_SNIFFER_MAC_FILTER_B3 0x25
#define CONFIG_SNIFFER_MAC_FILTER_B4 0x82
#define CONFIG_SNIFFER_MAC_FILTER_B5 0xF2
#define CONFIG_SNIFFER_MAC_FILTER_B6 0x74

#define CONFIG_ALL_CHANNEL_SCAN 1

#define CONFIG_SAVE_FREQUENCY_MINUTES 30

#define I2C_MASTER_NUM           I2C_NUM_0
#define I2C_MASTER_SCL_IO        PIN_SCL
#define I2C_MASTER_SDA_IO        PIN_SDA
#define I2C_MASTER_FREQ_HZ       50000
#define I2C_MASTER_TX_BUF_DISABLE 0
#define I2C_MASTER_RX_BUF_DISABLE 0

#endif
